### ISSUE TITLE
Get rid of `itertools` dependency

### ISSUE THREAD

**Issue by Empty2k12** [Empty2k12/influxdb-rust#10]
This is a dependency, not an application. We should pull in as few dependencies as possible. The current code can be replaced by more verbose code.

**Comment by mvucenovic** [comment]
Hi @Empty2k12, I've stumbled upon this issue via Hacktober label. I've sent you a pull request that should fix this issue, there really were not that many usages of itertools. Ping me if you have any comments

Also, applauding you for limiting the amount of dependencies in your libraries :)
