### ISSUE TITLE
Consider replacing `ToString` bound for more precise bound

### ISSUE THREAD

**Issue by pcpthm** [Empty2k12/influxdb-rust#24]
Currently, query builder accepts `ToString` for its arguments. But this trait doesn't have definite semantics and many types implement this. Most of the instances are irrelevant to database query, such as error types (because it implements `Display` for human display of the error).
I'm not sure why just accepting `String` or `impl Into<String>` is not enough. Probably it should be.

**Comment by Drevoed** [comment]
I share your thoughts about `Into<String>`, I have already converted usages of `ToString` to it in my wip branch.

**Comment by Empty2k12** [comment]
The idea was accepting both `&str` and `String`. I agree that using `Into<String>` is better.
