### ISSUE TITLE
Prefix `InfluxDb` of type names are redundant

### ISSUE THREAD

**Issue by pcpthm** [Empty2k12/influxdb-rust#25]
Because Rust has nice module system, naming prefixes are usually not used.
Because this crate only deal with the particular type of database, the prefix is really redundant.

**Comment by Empty2k12** [comment]
Agreed. Is this a best practice? How is working with two `Client`s done ergonomically (say `influxdb::client::Client` and `reqwest::Client`). Would you prefix them with the respective packages in those cases? I chose the `InfluxDb` prefix so there would be no such ambiguities.

**Comment by pcpthm** [comment]
(Assuming `influxdb::client::Client` made reexported to top-level)
Full path `influxdb::Client` and `reqwest::Client` are most used.
Sometimes aliases e.g. `use std::result::Result as StdResult;` are used.

**Comment by Empty2k12** [comment]
Reexporting to the top-level seems like the best solution indeed, thanks for the explanation.

Reexporting would be similar/better to #8

**Comment by Empty2k12** [comment]
Fixed in #27
