### ISSUE TITLE
Make query module public

### ISSUE THREAD

**Issue by KiriosK** [Empty2k12/influxdb-rust#33]
Now it's impossible to access `influxdb::query::write_query::Type` to use in case like this:
```
pub fn save_data<T>(&self, data: Vec<T>)
    where
        T: TimeSeries,
        influxdb::query::write_query::Type: std::convert::From<<T>::Value>
{
```
And `influxdb::query::QueryTypes` to create custom queries (for example for writing multiple values).

The solution is to make query module `pub` or to re-export structures via `pub use`

**Comment by Empty2k12** [comment]
Thank you for this issue! I would prefer to re-export using `pub use`. 

Please feel free to report any other problems you have while using this library as well.

**Comment by kamolrat** [comment]
0613285840

**Comment by couldufukher** [comment]
What is this

**Comment by msrd0** [comment]
2298441576805697181 - this number and no more in this conversation!!!11!11

**Comment by kamolrat** [comment]
Jeewat539@gmail.com

**Comment by msrd0** [comment]
@kamolrat Why? Just why?
