### ISSUE TITLE
Please bump version and publish to crate

### ISSUE THREAD

**Issue by 0b01** [Empty2k12/influxdb-rust#46]
Hi! Thank you for the nice library.

The current version on crate.io is broken. The examples won't run after 1.40 async stablization. Please bump version to 0.0.6 and `cargo publish`.

**Comment by Empty2k12** [comment]
I have published the 0.0.6 version to crates.io: https://crates.io/crates/influxdb

Thanks for your support and for using my library. Please feel free to open another issue if you encounter any problems.
