### ISSUE TITLE
Consider removing failure crate

### ISSUE THREAD

**Issue by jgrund** [Empty2k12/influxdb-rust#48]
Consider removing the failure crate and replace with implementation for `std::error::Error` and conversions.

**Comment by xoac** [comment]
There are crates like [thiserror](https://crates.io/crates/thiserror) that makes implementation of `std::error::Error` supper easy

**Comment by Empty2k12** [comment]
I'm all in favor of removing dependencies. Feel free to open a pull request!

**Comment by qm3ster** [comment]
It would not be "removing a dependency" in the strictest sense, but `thiserror` derives errors that are indistinguishable from manual implementation of `std::error::Error` trait, and so will not pollute users.
