### ISSUE TITLE
Whether to support async-std?

### ISSUE THREAD

**Issue by gmg137** [Empty2k12/influxdb-rust#58]
Is there any consideration to support async-std?

**Comment by Empty2k12** [comment]
I have never worked with `async-std`, is it easy to support both async-std and Tokio? If so PRs are open!

**Comment by gmg137** [comment]
I am not very clear, you may need to replace reqwest to isahc.

**Comment by JEnoch** [comment]
Hi @gmg137 ,
Working on integration InfluxDB in our project (eclipse-zenoh/zenoh#47) I would also be very interested to have `influxdb-rust` supporting `async-std`.
I made a quick experiment of porting it to `async-std = "1.6.5"` and `surf = "2.1.0"` [here](JEnoch/influxdb-rust@ebc20e80), and it seems to work find. However I have no clue on how to make it support both `async-std` and `tokio`! If you have some hint, I can work on that.
But if you're keen for a definitive switch to `async-std`, I can also do a PR of my changes.

**Comment by JEnoch** [comment]
Looking further it appears that [surf](https://crates.io/crates/surf) supports both `async-std` and `tokio` (as it relies on [http-client](https://crates.io/crates/http-client) that supports both).
I [added the code](https://github.com/JEnoch/influxdb-rust/commit/8bf1a744c4cb4631c79dfa4f7596b3fd826ef9dc) to run some tests with `async-std` and others with `tokio`, and it's fine.
I'll create a PR now.
