### ISSUE TITLE
tokio version =  "0.2.22"

### ISSUE THREAD

**Issue by Menzer05** [Empty2k12/influxdb-rust#85]
( panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.) 
this bug is caused by TOKIO version =  "0.2.22"  and  solved by tokio-rs/tokio#219

4

**Comment by msrd0** [comment]
Given that influxdb only has tokio as a dev-dependency, I don't think there's much this crate can do to fix this? If you want to use a newer version of tokio 0.2, you should be able to do so by running `cargo update`, or deleting your `Cargo.lock` file.
